//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18444
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.Phone.ServiceReference, version 3.7.0.0
// 
namespace FloK.ServiceReference1 {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Station", Namespace="http://schemas.datacontract.org/2004/07/FloKWS")]
    public partial class Station : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int address_cp_stationField;
        
        private int address_number_stationField;
        
        private string address_street_stationField;
        
        private string addresse_city_stationField;
        
        private int height_stationField;
        
        private int id_stationField;
        
        private int km_size_stationField;
        
        private double latitude_stationField;
        
        private double longitude_stationField;
        
        private string name_stationField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int address_cp_station {
            get {
                return this.address_cp_stationField;
            }
            set {
                if ((this.address_cp_stationField.Equals(value) != true)) {
                    this.address_cp_stationField = value;
                    this.RaisePropertyChanged("address_cp_station");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int address_number_station {
            get {
                return this.address_number_stationField;
            }
            set {
                if ((this.address_number_stationField.Equals(value) != true)) {
                    this.address_number_stationField = value;
                    this.RaisePropertyChanged("address_number_station");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string address_street_station {
            get {
                return this.address_street_stationField;
            }
            set {
                if ((object.ReferenceEquals(this.address_street_stationField, value) != true)) {
                    this.address_street_stationField = value;
                    this.RaisePropertyChanged("address_street_station");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string addresse_city_station {
            get {
                return this.addresse_city_stationField;
            }
            set {
                if ((object.ReferenceEquals(this.addresse_city_stationField, value) != true)) {
                    this.addresse_city_stationField = value;
                    this.RaisePropertyChanged("addresse_city_station");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int height_station {
            get {
                return this.height_stationField;
            }
            set {
                if ((this.height_stationField.Equals(value) != true)) {
                    this.height_stationField = value;
                    this.RaisePropertyChanged("height_station");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_station {
            get {
                return this.id_stationField;
            }
            set {
                if ((this.id_stationField.Equals(value) != true)) {
                    this.id_stationField = value;
                    this.RaisePropertyChanged("id_station");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int km_size_station {
            get {
                return this.km_size_stationField;
            }
            set {
                if ((this.km_size_stationField.Equals(value) != true)) {
                    this.km_size_stationField = value;
                    this.RaisePropertyChanged("km_size_station");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double latitude_station {
            get {
                return this.latitude_stationField;
            }
            set {
                if ((this.latitude_stationField.Equals(value) != true)) {
                    this.latitude_stationField = value;
                    this.RaisePropertyChanged("latitude_station");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double longitude_station {
            get {
                return this.longitude_stationField;
            }
            set {
                if ((this.longitude_stationField.Equals(value) != true)) {
                    this.longitude_stationField = value;
                    this.RaisePropertyChanged("longitude_station");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name_station {
            get {
                return this.name_stationField;
            }
            set {
                if ((object.ReferenceEquals(this.name_stationField, value) != true)) {
                    this.name_stationField = value;
                    this.RaisePropertyChanged("name_station");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/GetNearestStations", ReplyAction="http://tempuri.org/IService1/GetNearestStationsResponse")]
        System.IAsyncResult BeginGetNearestStations(double myLatitude, double myLongitude, float km, System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<FloK.ServiceReference1.Station> EndGetNearestStations(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/GetAllStations", ReplyAction="http://tempuri.org/IService1/GetAllStationsResponse")]
        System.IAsyncResult BeginGetAllStations(System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<FloK.ServiceReference1.Station> EndGetAllStations(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/isLoginInDB", ReplyAction="http://tempuri.org/IService1/isLoginInDBResponse")]
        System.IAsyncResult BeginisLoginInDB(string login, System.AsyncCallback callback, object asyncState);
        
        bool EndisLoginInDB(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/isUserInDB", ReplyAction="http://tempuri.org/IService1/isUserInDBResponse")]
        System.IAsyncResult BeginisUserInDB(string login, string password, System.AsyncCallback callback, object asyncState);
        
        bool EndisUserInDB(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/CreateUser", ReplyAction="http://tempuri.org/IService1/CreateUserResponse")]
        System.IAsyncResult BeginCreateUser(string login, string mail, string pwd, System.AsyncCallback callback, object asyncState);
        
        bool EndCreateUser(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : FloK.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetNearestStationsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetNearestStationsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<FloK.ServiceReference1.Station> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<FloK.ServiceReference1.Station>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetAllStationsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetAllStationsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<FloK.ServiceReference1.Station> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<FloK.ServiceReference1.Station>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class isLoginInDBCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public isLoginInDBCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public bool Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class isUserInDBCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public isUserInDBCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public bool Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CreateUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public CreateUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public bool Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<FloK.ServiceReference1.IService1>, FloK.ServiceReference1.IService1 {
        
        private BeginOperationDelegate onBeginGetNearestStationsDelegate;
        
        private EndOperationDelegate onEndGetNearestStationsDelegate;
        
        private System.Threading.SendOrPostCallback onGetNearestStationsCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetAllStationsDelegate;
        
        private EndOperationDelegate onEndGetAllStationsDelegate;
        
        private System.Threading.SendOrPostCallback onGetAllStationsCompletedDelegate;
        
        private BeginOperationDelegate onBeginisLoginInDBDelegate;
        
        private EndOperationDelegate onEndisLoginInDBDelegate;
        
        private System.Threading.SendOrPostCallback onisLoginInDBCompletedDelegate;
        
        private BeginOperationDelegate onBeginisUserInDBDelegate;
        
        private EndOperationDelegate onEndisUserInDBDelegate;
        
        private System.Threading.SendOrPostCallback onisUserInDBCompletedDelegate;
        
        private BeginOperationDelegate onBeginCreateUserDelegate;
        
        private EndOperationDelegate onEndCreateUserDelegate;
        
        private System.Threading.SendOrPostCallback onCreateUserCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<GetNearestStationsCompletedEventArgs> GetNearestStationsCompleted;
        
        public event System.EventHandler<GetAllStationsCompletedEventArgs> GetAllStationsCompleted;
        
        public event System.EventHandler<isLoginInDBCompletedEventArgs> isLoginInDBCompleted;
        
        public event System.EventHandler<isUserInDBCompletedEventArgs> isUserInDBCompleted;
        
        public event System.EventHandler<CreateUserCompletedEventArgs> CreateUserCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult FloK.ServiceReference1.IService1.BeginGetNearestStations(double myLatitude, double myLongitude, float km, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetNearestStations(myLatitude, myLongitude, km, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<FloK.ServiceReference1.Station> FloK.ServiceReference1.IService1.EndGetNearestStations(System.IAsyncResult result) {
            return base.Channel.EndGetNearestStations(result);
        }
        
        private System.IAsyncResult OnBeginGetNearestStations(object[] inValues, System.AsyncCallback callback, object asyncState) {
            double myLatitude = ((double)(inValues[0]));
            double myLongitude = ((double)(inValues[1]));
            float km = ((float)(inValues[2]));
            return ((FloK.ServiceReference1.IService1)(this)).BeginGetNearestStations(myLatitude, myLongitude, km, callback, asyncState);
        }
        
        private object[] OnEndGetNearestStations(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<FloK.ServiceReference1.Station> retVal = ((FloK.ServiceReference1.IService1)(this)).EndGetNearestStations(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetNearestStationsCompleted(object state) {
            if ((this.GetNearestStationsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetNearestStationsCompleted(this, new GetNearestStationsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetNearestStationsAsync(double myLatitude, double myLongitude, float km) {
            this.GetNearestStationsAsync(myLatitude, myLongitude, km, null);
        }
        
        public void GetNearestStationsAsync(double myLatitude, double myLongitude, float km, object userState) {
            if ((this.onBeginGetNearestStationsDelegate == null)) {
                this.onBeginGetNearestStationsDelegate = new BeginOperationDelegate(this.OnBeginGetNearestStations);
            }
            if ((this.onEndGetNearestStationsDelegate == null)) {
                this.onEndGetNearestStationsDelegate = new EndOperationDelegate(this.OnEndGetNearestStations);
            }
            if ((this.onGetNearestStationsCompletedDelegate == null)) {
                this.onGetNearestStationsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetNearestStationsCompleted);
            }
            base.InvokeAsync(this.onBeginGetNearestStationsDelegate, new object[] {
                        myLatitude,
                        myLongitude,
                        km}, this.onEndGetNearestStationsDelegate, this.onGetNearestStationsCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult FloK.ServiceReference1.IService1.BeginGetAllStations(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetAllStations(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<FloK.ServiceReference1.Station> FloK.ServiceReference1.IService1.EndGetAllStations(System.IAsyncResult result) {
            return base.Channel.EndGetAllStations(result);
        }
        
        private System.IAsyncResult OnBeginGetAllStations(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((FloK.ServiceReference1.IService1)(this)).BeginGetAllStations(callback, asyncState);
        }
        
        private object[] OnEndGetAllStations(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<FloK.ServiceReference1.Station> retVal = ((FloK.ServiceReference1.IService1)(this)).EndGetAllStations(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetAllStationsCompleted(object state) {
            if ((this.GetAllStationsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetAllStationsCompleted(this, new GetAllStationsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetAllStationsAsync() {
            this.GetAllStationsAsync(null);
        }
        
        public void GetAllStationsAsync(object userState) {
            if ((this.onBeginGetAllStationsDelegate == null)) {
                this.onBeginGetAllStationsDelegate = new BeginOperationDelegate(this.OnBeginGetAllStations);
            }
            if ((this.onEndGetAllStationsDelegate == null)) {
                this.onEndGetAllStationsDelegate = new EndOperationDelegate(this.OnEndGetAllStations);
            }
            if ((this.onGetAllStationsCompletedDelegate == null)) {
                this.onGetAllStationsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetAllStationsCompleted);
            }
            base.InvokeAsync(this.onBeginGetAllStationsDelegate, null, this.onEndGetAllStationsDelegate, this.onGetAllStationsCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult FloK.ServiceReference1.IService1.BeginisLoginInDB(string login, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginisLoginInDB(login, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        bool FloK.ServiceReference1.IService1.EndisLoginInDB(System.IAsyncResult result) {
            return base.Channel.EndisLoginInDB(result);
        }
        
        private System.IAsyncResult OnBeginisLoginInDB(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string login = ((string)(inValues[0]));
            return ((FloK.ServiceReference1.IService1)(this)).BeginisLoginInDB(login, callback, asyncState);
        }
        
        private object[] OnEndisLoginInDB(System.IAsyncResult result) {
            bool retVal = ((FloK.ServiceReference1.IService1)(this)).EndisLoginInDB(result);
            return new object[] {
                    retVal};
        }
        
        private void OnisLoginInDBCompleted(object state) {
            if ((this.isLoginInDBCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.isLoginInDBCompleted(this, new isLoginInDBCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void isLoginInDBAsync(string login) {
            this.isLoginInDBAsync(login, null);
        }
        
        public void isLoginInDBAsync(string login, object userState) {
            if ((this.onBeginisLoginInDBDelegate == null)) {
                this.onBeginisLoginInDBDelegate = new BeginOperationDelegate(this.OnBeginisLoginInDB);
            }
            if ((this.onEndisLoginInDBDelegate == null)) {
                this.onEndisLoginInDBDelegate = new EndOperationDelegate(this.OnEndisLoginInDB);
            }
            if ((this.onisLoginInDBCompletedDelegate == null)) {
                this.onisLoginInDBCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnisLoginInDBCompleted);
            }
            base.InvokeAsync(this.onBeginisLoginInDBDelegate, new object[] {
                        login}, this.onEndisLoginInDBDelegate, this.onisLoginInDBCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult FloK.ServiceReference1.IService1.BeginisUserInDB(string login, string password, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginisUserInDB(login, password, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        bool FloK.ServiceReference1.IService1.EndisUserInDB(System.IAsyncResult result) {
            return base.Channel.EndisUserInDB(result);
        }
        
        private System.IAsyncResult OnBeginisUserInDB(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string login = ((string)(inValues[0]));
            string password = ((string)(inValues[1]));
            return ((FloK.ServiceReference1.IService1)(this)).BeginisUserInDB(login, password, callback, asyncState);
        }
        
        private object[] OnEndisUserInDB(System.IAsyncResult result) {
            bool retVal = ((FloK.ServiceReference1.IService1)(this)).EndisUserInDB(result);
            return new object[] {
                    retVal};
        }
        
        private void OnisUserInDBCompleted(object state) {
            if ((this.isUserInDBCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.isUserInDBCompleted(this, new isUserInDBCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void isUserInDBAsync(string login, string password) {
            this.isUserInDBAsync(login, password, null);
        }
        
        public void isUserInDBAsync(string login, string password, object userState) {
            if ((this.onBeginisUserInDBDelegate == null)) {
                this.onBeginisUserInDBDelegate = new BeginOperationDelegate(this.OnBeginisUserInDB);
            }
            if ((this.onEndisUserInDBDelegate == null)) {
                this.onEndisUserInDBDelegate = new EndOperationDelegate(this.OnEndisUserInDB);
            }
            if ((this.onisUserInDBCompletedDelegate == null)) {
                this.onisUserInDBCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnisUserInDBCompleted);
            }
            base.InvokeAsync(this.onBeginisUserInDBDelegate, new object[] {
                        login,
                        password}, this.onEndisUserInDBDelegate, this.onisUserInDBCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult FloK.ServiceReference1.IService1.BeginCreateUser(string login, string mail, string pwd, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginCreateUser(login, mail, pwd, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        bool FloK.ServiceReference1.IService1.EndCreateUser(System.IAsyncResult result) {
            return base.Channel.EndCreateUser(result);
        }
        
        private System.IAsyncResult OnBeginCreateUser(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string login = ((string)(inValues[0]));
            string mail = ((string)(inValues[1]));
            string pwd = ((string)(inValues[2]));
            return ((FloK.ServiceReference1.IService1)(this)).BeginCreateUser(login, mail, pwd, callback, asyncState);
        }
        
        private object[] OnEndCreateUser(System.IAsyncResult result) {
            bool retVal = ((FloK.ServiceReference1.IService1)(this)).EndCreateUser(result);
            return new object[] {
                    retVal};
        }
        
        private void OnCreateUserCompleted(object state) {
            if ((this.CreateUserCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CreateUserCompleted(this, new CreateUserCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CreateUserAsync(string login, string mail, string pwd) {
            this.CreateUserAsync(login, mail, pwd, null);
        }
        
        public void CreateUserAsync(string login, string mail, string pwd, object userState) {
            if ((this.onBeginCreateUserDelegate == null)) {
                this.onBeginCreateUserDelegate = new BeginOperationDelegate(this.OnBeginCreateUser);
            }
            if ((this.onEndCreateUserDelegate == null)) {
                this.onEndCreateUserDelegate = new EndOperationDelegate(this.OnEndCreateUser);
            }
            if ((this.onCreateUserCompletedDelegate == null)) {
                this.onCreateUserCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCreateUserCompleted);
            }
            base.InvokeAsync(this.onBeginCreateUserDelegate, new object[] {
                        login,
                        mail,
                        pwd}, this.onEndCreateUserDelegate, this.onCreateUserCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override FloK.ServiceReference1.IService1 CreateChannel() {
            return new Service1ClientChannel(this);
        }
        
        private class Service1ClientChannel : ChannelBase<FloK.ServiceReference1.IService1>, FloK.ServiceReference1.IService1 {
            
            public Service1ClientChannel(System.ServiceModel.ClientBase<FloK.ServiceReference1.IService1> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginGetNearestStations(double myLatitude, double myLongitude, float km, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[3];
                _args[0] = myLatitude;
                _args[1] = myLongitude;
                _args[2] = km;
                System.IAsyncResult _result = base.BeginInvoke("GetNearestStations", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<FloK.ServiceReference1.Station> EndGetNearestStations(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<FloK.ServiceReference1.Station> _result = ((System.Collections.ObjectModel.ObservableCollection<FloK.ServiceReference1.Station>)(base.EndInvoke("GetNearestStations", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetAllStations(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("GetAllStations", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<FloK.ServiceReference1.Station> EndGetAllStations(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<FloK.ServiceReference1.Station> _result = ((System.Collections.ObjectModel.ObservableCollection<FloK.ServiceReference1.Station>)(base.EndInvoke("GetAllStations", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginisLoginInDB(string login, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = login;
                System.IAsyncResult _result = base.BeginInvoke("isLoginInDB", _args, callback, asyncState);
                return _result;
            }
            
            public bool EndisLoginInDB(System.IAsyncResult result) {
                object[] _args = new object[0];
                bool _result = ((bool)(base.EndInvoke("isLoginInDB", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginisUserInDB(string login, string password, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[2];
                _args[0] = login;
                _args[1] = password;
                System.IAsyncResult _result = base.BeginInvoke("isUserInDB", _args, callback, asyncState);
                return _result;
            }
            
            public bool EndisUserInDB(System.IAsyncResult result) {
                object[] _args = new object[0];
                bool _result = ((bool)(base.EndInvoke("isUserInDB", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginCreateUser(string login, string mail, string pwd, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[3];
                _args[0] = login;
                _args[1] = mail;
                _args[2] = pwd;
                System.IAsyncResult _result = base.BeginInvoke("CreateUser", _args, callback, asyncState);
                return _result;
            }
            
            public bool EndCreateUser(System.IAsyncResult result) {
                object[] _args = new object[0];
                bool _result = ((bool)(base.EndInvoke("CreateUser", _args, result)));
                return _result;
            }
        }
    }
}
